# -*- coding: utf-8 -*-
"""mojeWizualizacje.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JuZqokuC3TQBwOZELit8rpJ54mLdJPT4
"""

#0. WSTĘP
print('To mój notatnik z wizualizacji danych.','Made by Mikołaj Plata', sep = '\n')

# Commented out IPython magic to ensure Python compatibility.
#1. IMPORT BIBLIOTEK
import pandas as pd
import matplotlib.pyplot as plt
from pandas.plotting import register_matplotlib_converters
# %matplotlib inline
register_matplotlib_converters()

#2. RYSOWANIE PIERWSZEGO WYKRESU
fig, ax = plt.subplots()
x = list(range(4))
y = list(range(4))
#2.1 WYKRES Z ATRYBUTAMI
ax.plot(x,y, marker = 'v', color = 'r', linestyle = '--')
#marker, kolor i styl linii

#3. APLIKOWANIE PARAMETRÓW
ax.grid(visible = True, axis = 'both')    #siatka
ax.set_title('Tytuł wykresu')   #tytuł wykresu
ax.set_xlabel('Nazwa osi x')    #nazwa osi X
ax.set_ylabel('Nazwa osi y')    #nazwa osi Y

plt.show()

#4. WALKA Z PIERWSZĄ CSV-ką
n = 20 
apple = pd.read_csv('https://raw.githubusercontent.com/matzim95/ML-datasets/master/apple.csv', parse_dates = True, index_col = 'Date')
fig, ax = plt.subplots()
ax.plot(apple.index[:n], apple['High'][:n], color = 'r', marker = 'o')    #pierwszy wykres - cena maksymalna
ax.plot(apple.index[:n], apple['Low'][:n], color = 'b', marker = 'v')   #drugi wykres - cena minimalna

#4.1 DODAJEMY PARAMETRY WYKRESU
ax.set_title('Pierwszy csv - Cena jabłek')
ax.set_xlabel('Rok badania')
ax.set_ylabel('Cena jabłka')
ax.xaxis.set_tick_params(rotation = 90)   #kąt indeksów osi x
ax.yaxis.set_tick_params(rotation = 360)    #kąt indeksów osi y

plt.show()